### PR TITLE
[WIP] Using wastewater data to monitor SARS-CoV-2 in England

### PR DESCRIPTION
**Pull request by AoifeHughes**
### Summary

Created the story as outlined in issue: https://github.com/alan-turing-institute/TuringDataStories/issues/193 

### List of changes proposed in this PR (pull-request)

- Adds a python jupyter notebook story
- Several data files used in the story 
- Instructions on how to prepare data for analysis

### What should a reviewer concentrate their feedback on?

- [ ] Amount of background information
- [ ] Visuals are clear 
- [ ] techniques are explained clearly 
- [ ] Reasoning is made clear 
- [ ] General suggestions to increase quality of notebook
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: AoifeHughes

### CODE REVIEW

**Comment by crangelsmith** [comment]
Thank you @AoifeHughes! We prefer not to store the data here in the TDS repo, could you put the data somewhere citable like [Zenodo](https://zenodo.org/) and then in the notebook download it and load it?

**Comment by AoifeHughes** [comment]
Yes! Will move the data out and update soon!

**Comment by AoifeHughes** [comment]
Commit #[9692c20](https://github.com/alan-turing-institute/TuringDataStories/pull/206/commits/9692c2012a1108c554683ded5e976c1d91e6bd34) has added a link and download code for the data

**Comment by AoifeHughes** [comment]
<p>✅</p>

---

 <a href='https://app.reviewnb.com/alan-turing-institute/TuringDataStories/pull/206/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AoifeHughes** [comment]
<ul><li>[ ]</li></ul>

---

 <a href='https://app.reviewnb.com/alan-turing-institute/TuringDataStories/pull/206/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AoifeHughes** [comment]
<p>https://github.com/alan-turing-institute/TuringDataStories/pull/206/commits/4e57d5be93fec1f889dfdc82fbed2cd93f1a3366 - solves this and a few prior points. </p>

---

 <a href='https://app.reviewnb.com/alan-turing-institute/TuringDataStories/pull/206/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AoifeHughes** [comment]
<p>Completely agree, the variable namings are horrible here - will take a minute to actually sort these out, though! Will come back to this one</p>

---

 <a href='https://app.reviewnb.com/alan-turing-institute/TuringDataStories/pull/206/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AoifeHughes** [comment]
<p>Mentioned in the section <code># weather data </code> have added clarity also</p>

---

 <a href='https://app.reviewnb.com/alan-turing-institute/TuringDataStories/pull/206/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AoifeHughes** [comment]
*Super important* point raised during review that needs to be done after solving other issues (so as not to have to repeat, or diverge again)
- [ ] Refactor naming of modelling variables to make more sense
- [ ] Create consistency of variable names
- [ ] Add clarity in array values and match with names in equations

**Pull request closed without merging**
