### PR TITLE
fix small typo

### PR DESCRIPTION
**Pull request by yochannah**
### Summary

spotted an extra "and" in the readme :)

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by DavidBeavan** [comment]
@all-contributors please add @yochannah  for mentoring and documentation

**Comment by DavidBeavan** [comment]
@all-contributors please add @yochannah for mentoring

**Comment by DavidBeavan** [comment]
@all-contributors please add @yochannah for 🧑‍🏫

**Comment by crangelsmith** [comment]
@all-contributors please add @yochannah for mentoring

**Comment by crangelsmith** [comment]
@all-contributors please add @yochannah for ideas

**Pull request merged**
