### PR TITLE
[Turing Data Story] Election model

### LINKED ISSUE #108: [Turing Data Story] US election data story
# Story description 

Using Bayesian inference to predict the final outcomes of the elections in the states of Arizona, Pennsylvania and Georgia and updating the prediction with each new set of ballots that come in.

**Which datasets will you be using in this Turing Data Story?**

Data from 
https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html

**Additional context**

This story was born from a Turing slack group where we discussed the election results during the election night/week and month. 

# Current status

 - [x] Write story outline
 - [x] Add material to the story notebook
 - [x] Combine materials into a readable story
 - [x] Proofread
 - [x] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

### LINKED ISSUE #113: [Review][Turing Data Story] Election model
# Story Review:  

**Story Name:** US election model

**Submitting Author**: @edaub 

**Pull Request:** #111 

**Reviewers:** @samvanstroud @kevinxufs 

## Reviewer instructions & questions

@samvanstroud @kevinxufs , please carry out your review in this issue by updating the checklist below, and writing new comments in case you have any questions. If you cannot edit the checklist please:

- Make sure you're logged in to your GitHub account
- Be sure to accept the invite at this URL: https://github.com/alan-turing-institute/TuringDataStories/settings/access

Any questions, concerns or suggestions regarding the review process please let @crangelsmith, @DavidBeavan or @samvanstroud know.

✨ Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest ✨

#### Code of conduct
- [ ] I confirm that I read and will adhere to the Turing Data Stories [code of conduct](https://github.com/alan-turing-institute/TuringDataStories/blob/master/CODE_OF_CONDUCT.md).

#### General checks
- [ ]  **Notebook:** Is the source code for this data story available as a notebook in the linked pull request?
- [ ]  **Contribution and authorship:** Are the authors clearly listed? Does the author list seem appropriate and complete?
- [ ] **Scope and eligibility:** Does the submission contain an original and complete analysis of open data? Is the story aligned with the Turing Data Stories [vision statment](https://github.com/alan-turing-institute/TuringDataStories#our-vision)?

#### Reproducibility
- [ ] Does the notebook run in a local environment?
- [ ] Does the notebook build and run in binder?
- [ ] Are all data sources openly accessible and properly cited with a link?
- [ ] Is the data provenance documented and transparent?

#### Pedagogy
- [ ] Does the story demonstrate some specific data analysis or visualisation techniques?
- [ ] Are these techniques well motivated?
- [ ] Are these techniques well implemented?
- [ ] Is the notebook well documented, using both markdown cells and comments in code cells?
- [ ] Does the notebook has a introduction section motivating the story?
- [ ] Does the notebook has a conclusion section discussing the main insight from the stories?
- [ ] Is the paper well written (it does not require editing for structure, language, or writing quality)?

#### Context
- [ ] Does the story give an insight into some societal issue?
- [ ] Is the context around this issue well referenced (newspaper articles, scientific papers, etc.)?

## AOB

There are a few other checkboxes in the PR #111  proposed by @edaub that should be checked: 

- [ ] Does the model give enough context about the election, both for the US election format in general as well as the particular situation that arose in 2020?
- [ ] Do I give enough detail about the linear regression models, and is it clear why it is hard to draw conclusions from them?
- [ ] Is there enough background on Bayesian Inference for non-specialists?
- [ ] Is it clear what a hierarchical model is and why it makes sense in this situation?
- [ ] Is the model itself described in sufficient detail? Too much detail?
- [ ] Do the results get tied back to the election narrative enough to make the story of interest to readers that don't care as much about the model details?
- [ ] Is the coding style sensible? I try to wrap everything into functions out of habit, but sometimes this makes notebooks harder to read.
- [ ] Everything looks ok?

### PR DESCRIPTION
**Pull request by edaub**
### Summary

New story using a Bayesian Hierarchical model to examine the mail votes for several battleground states in the 2020 US Presidential Election. Implements the model in a markdown file/notebook with additional documentation/requirements specificiations. Fixes #108.

### List of changes proposed in this PR (pull-request)

* New files implementing the story iself
  * `mail_vote_model.md` is the original markdown file that I used to write the story. Because the output includes several large animation files, I wanted to minimize the number of commits containing large files to reduce bloat in the repo.
  * `battleground-state-changes.csv` is the latest version of the CSV as a fallback in case the latest one cannot be obtained from the scraper website.
  * `mail_vote_model.ipynb` is the markdown file converted to a notebook and executed so that it contains all outputs. Note that the animations are very expensive to produce (takes several hours for each one) so I have tried to minimize the number of times the notebook needs to be executed.
  * `mail_vote_model.html` is a static HTML version containing all outputs (including the expensive animations) for situations where the notebook cannot be displayed.
  * `Makefile` includes recipes for converting from markdown to the (unexecuted) notebook and from the (executed) notebook to HTML.
  * `requirements.txt` includes all requirements for running the notebook code. This is also included in the Binder YAML file. Also includes the package needed to convert from markdown to notebook.
  * `README.md` describes the model, how to install dependencies, and convert between different formats.
  * `.gitignore` file to ignore the model outputs that are cached to disk to avoid re-drawing MCMC samples when appropriate.
* `environment.yml` file in the Binder directory has been updated to include additional dependencies for running the notebook.

### What should a reviewer concentrate their feedback on?

- [x] Does the model give enough context about the election, both for the US election format in general as well as the particular situation that arose in 2020?
- [x] Do I give enough detail about the linear regression models, and is it clear why it is hard to draw conclusions from them?
- [x] Is there enough background on Bayesian Inference for non-specialists?
- [x] Is it clear what a hierarchical model is and why it makes sense in this situation?
- [x] Is the model itself described in sufficient detail? Too much detail?
- [x] Do the results get tied back to the election narrative enough to make the story of interest to readers that don't care as much about the model details?
- [x] Is the coding style sensible? I try to wrap everything into functions out of habit, but sometimes this makes notebooks harder to read.
- [x] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: @edaub, possibly @martintoreilly who contributed to the ideas in this story.

### CODE REVIEW

**Comment by crangelsmith** [comment]
Hi @edaub, this is great thanks!! We will start the review process, @samvanstroud and @kevinxufs are going to be the reviewers. A couple of comments:
1. We might need to do some formatting changes to the notebook to make it compatible with the fast pages interface, I hope this is Ok. 
2. As we are very close to the Christmas break we might not finish the review until the new year, but we hope to have this published sometime in January. 

I'll open the review issue now.

**Comment by crangelsmith** [comment]
@all-contributors please add @edaub  for blog

**Comment by crangelsmith** [comment]
@all-contributors please add @edaub for code

**Comment by crangelsmith** [comment]
@all-contributors please add @edaub for ideas

**Comment by crangelsmith** [comment]
@all-contributors please add @edaub for content

**Comment by crangelsmith** [comment]
@all-contributors please add @martintoreilly for ideas

**Comment by crangelsmith** [comment]
@all-contributors please add @martintoreilly for ideas

**Comment by edaub** [comment]
No problem, @crangelsmith! Thanks for the help with this and whenever they have a chance to review I am sure it will be helpful.

**Comment by samvanstroud** [comment]
Hi @edaub, thanks for submitting this! @kevinxufs and I are getting started with our reviews, we hope to have them done in a week's time. The reviews will happen at https://github.com/alan-turing-institute/TuringDataStories/issues/113.

**Comment by edaub** [comment]
I've pushed my final updates to the markdown file, and I think I am happy with this version. In addition to the revisions suggested and discussed in #113, I ended up refactoring some of the code for modularity/clarity, including the animations.

I still need to convert to a notebook and run the expensive simulations. @crangelsmith Do we know the best way to handle the  animations for the final version? I'm not sure how the deployment occurs -- will the saved notebook be published unexecuted, shown directly as I save it, or automatically run again when it is published? Similarly, if we want to publish an HTML version that will show the animations but not let the other code be executed, do we know how this might work? Happy to help out in managing this however I can -- I certainly don't want to make more effort for you!

**Comment by crangelsmith** [comment]
Hi @edaub , thanks for this, we will be publishing the story imminently :D

About the format for the final version, I think @samvanstroud did a check before and the executed notebook renders nicely in fast pages, so we might not have to do much on that side. He can confirm this. 

Also I wanted to tell you that I plan to use this story for a hand-on session i'll be running with some masters students from Latinoamerica, I think is an amazing example for them to learn about Bayesian modelling. For this I'm going to translate the notebook to Spanish and will add it to the repo.

**Comment by edaub** [comment]
Yes, feel free to use this in future educational opportunities.

I will run the notebooks again then and commit the final executed notebook. I won't commit a new HTML version and will delete it from the final commit. I'll let you know with a comment here that it is ready to merge.

**Comment by samvanstroud** [comment]
Hi @edaub, really sorry, I have jumped the gun a bit (not staying on top of this thread) and ran the notebook on my end and have pushed it here. If there are any problems let me know and I will roll back the changes (which also rename the notebook file as required by fastpages). If things look ok to you, then I think we can go ahead and merge this!

**Comment by edaub** [comment]
@samvanstroud No worries -- I have a couple of local changes that I haven't pushed but I will pull your changes and rebase on top of that. I presume I should make sure the final notebook gets moved to the path you specify for publication purposes?

**Comment by samvanstroud** [comment]
@edaub, sounds good. Yep., the timestamped path I introduce will help keep things organised on our end, thanks!

**Comment by samvanstroud** [comment]
@edaub, just a friendly nudge, it will be great to get this merged.

**Comment by edaub** [comment]
Thanks for the reminder -- the last week has been a bit crazy but I finally found an hour to read it over one last time. I just pushed the final version that I am happy with, so feel free to go ahead and merge/publish.

I'm happy to fix the conflicts, though I suspect you know better than I do which is the correct version so I will assume someone else is fixing this unless I hear otherwise.

Also, you can squash merge this if you don't want extra copies of the big notebook in the repo -- I don't need the previous versions hanging around for any reason, so up to you how you handle the merge.

**Comment by samvanstroud** [comment]
Ok, I resolved the conflicts and re-ran the notebook locally just for good measure (they appeared to be missing on my end). Merging now!

**Pull request merged**
