### PR TITLE
update notebook after adding missing spotify data

### PR DESCRIPTION
**Pull request by billfinnegan**
### Summary

Desert Island Discs story: We discovered missing Spotify data for the most recent 60 episodes. This commit includes the updated XLSX file (which also needs to be added to HCommons) and an updated version of the notebook after running the latest data.

### List of changes proposed in this PR (pull-request)

* New data file.
* Updated notebook (mostly narrative changes)

### What should a reviewer concentrate their feedback on?

- [ ] Only real changes in analysis come halfway into the notebook, when getting into genres/artists, so could run through that.
- [ ] Everything looks ok?

### Acknowledging contributors

- [X] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by billfinnegan** [comment]
Now there are three commits on this: update to the notebook based on the data addendum, another update once the data link was updated on hcommons, and finally a markdown edit to resolve a formatting issue on the live story.

**Comment by samvanstroud** [comment]
Looks great thanks @billfinnegan ! I guess we can remove the `xlsx` files you add here though, now the HC deposit is updated?

**Comment by billfinnegan** [comment]
Good point - one more commit with the excel file removed...

**Comment by samvanstroud** [comment]
Ok thanks @billfinnegan! feel free to merge this when ready :)

**Pull request merged**
