### PR TITLE
TDS Modelling Hospital Admissions in the UK

### LINKED ISSUE #149: [Turing Data Story] Modeling Hospital Admissions in the UK
# Story description 

Story to create a model of hospital admissions in the fall pandemic in the UK and uses it to predict the course of the summer third wave.

**Which datasets will you be using in this Turing Data Story?**

[UK Government Covid Data](https://coronavirus.data.gov.uk/)

**Additional context**

The idea of this story originated in a speech by Health Secretary Sajid Javid on [28 June 2021](https://hansard.parliament.uk/Commons/2021-06-28/debates/16849758-096E-4650-B84D-643DF5458417/Covid-19Update).

# Ethical guideline 

Ideally a Turing Data Story has these properties and follows the [5 safes framework](http://blog.ukdataservice.ac.uk/access-to-sensitive-data-for-research-the-5-safes/).

- [x] The analysis you produce is openly available and reproducible.
- [x] Any data used are [open](https://opendatahandbook.org/guide/en/what-is-open-data/) and have an explicit licence, provenance and attribution.
- [x] Any data used are not [personal data](https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/key-definitions/what-is-personal-data/) (i.e. the data is anonymous or anonymised).
- [x] Any linkage of datasets in your data story does not lead to an increased risk of the personal identification of individuals.
- [x] The Story must be truthful and clear about any limitations of analysis (and potential biases in data).
- [x] The Story will not lead to negative social outcomes, such as (but not limited to) increasing discrimination or injustice.

# Current status

 - [x] Scoping of the story
 - [x] Write story outline
 - [x] Add material to the story notebook
 - [x] Combine materials into a readable story
 - [x] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

### PR DESCRIPTION
**Pull request by edaub**
### Summary

Fixes #149 

Adds story examining hospital admissions in England during the second and third waves of Covid-19.

### List of changes proposed in this PR (pull-request)

* New story carrying out Bayesian modelling of hospital admissions in England.

### What should a reviewer concentrate their feedback on?

- [ ] Is the context of the story well described?
- [ ] Is the model clear and understandable?
- [ ] Is the model implementation clear and understandable?
- [ ] Do I sufficiently cover the caveats in the analysis?
- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by crangelsmith** [comment]
Hi Eric, thank you very much for this new story! I have set up the review issue in #152, @helendduncan, @ChristinaLast and @lukehare will be the reviewers of this story. 

@edaub Could I ask you to write a small abstract about the story that we can pass on to Comms once we publish it? You can just write it in here as a comment. Thank you!

**Comment by ChristinaLast** [comment]
@edaub Assigned you to take a look at some of the reproducibility issues. Let me know how you get on!

**Review by helen-d-little — COMMENTED** [review]
Some comments left in the notebook RE timings of lockdowns and wall clock timing of running notebook locally. Did not check for binder.

**Comment by edaub** [comment]
I appreciate the comments -- hoping to tackle this in the next week or so (though no rush @lukehare -- I'd rather get thoughtful comments later than ones that are hurried because I'm going on holiday...)

**Review by ChristinaLast — APPROVED** [review]
This looks great @edaub, thanks forthe adjustments 🎉

**Review by lukehare — APPROVED** [review]
Looks good to me - thanks, @edaub!

**Comment by ChristinaLast** [comment]
Ah, I wasnt aware they were merged. I can create a `hotfix` branch to remove and add to `.gitignore`?

**Comment by crangelsmith** [comment]
> Ah, I wasnt aware they were merged. I can create a `hotfix` branch to remove and add to `.gitignore`?

Sounds great! Thanks!

**Comment by ChristinaLast** [comment]
So @crangelsmith the hotfix PR is [here](https://github.com/alan-turing-institute/TuringDataStories/pull/164). Please feel free to approve and I can merge. Apologies for those files getting into `master`!

**Pull request merged**
